<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="AddCustomerLoginTest"
           tests="3"
           failures="2"
           errors="0"
           skipped="0"
           time="21.330">
  <properties />
            <testcase name="addCustomer" time="10.048" classname="testCases.TC_002_AddCustomerLoginTest">
                <failure type="java.lang.AssertionError"
                  message="Customer not added successfully"
              >
<![CDATA[java.lang.AssertionError: Customer not added successfully
  org.testng.Assert.fail(Assert.java:111)
  testCases.TC_002_AddCustomerLoginTest.addCustomer(TC_002_AddCustomerLoginTest.java:58)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:566)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
  org.testng.TestRunner.privateRun(TestRunner.java:848)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
  org.testng.SuiteRunner.run(SuiteRunner.java:336)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
  org.testng.TestNG.runSuites(TestNG.java:1114)
  org.testng.TestNG.run(TestNG.java:1082)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
  org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
  org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
      </failure>

          </testcase>
            <testcase name="addCustomer" time="10.078" classname="testCases.TC_002_AddCustomerLoginTest">
                <failure type="java.lang.AssertionError"
                  message="Customer not added successfully"
              >
<![CDATA[java.lang.AssertionError: Customer not added successfully
  org.testng.Assert.fail(Assert.java:111)
  testCases.TC_002_AddCustomerLoginTest.addCustomer(TC_002_AddCustomerLoginTest.java:58)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:566)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
  org.testng.TestRunner.privateRun(TestRunner.java:848)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
  org.testng.SuiteRunner.run(SuiteRunner.java:336)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
  org.testng.TestNG.runSuites(TestNG.java:1114)
  org.testng.TestNG.run(TestNG.java:1082)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
  org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
  org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="addCustomer" time="1.204" classname="testCases.TC_002_AddCustomerLoginTest" />
      
</testsuite>
